[build]
  base    = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_BACKEND_URL = ""

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
